Better and more robust script

diff --git a/make-package-debian b/make-package-debian
--- a/make-package-debian
+++ b/make-package-debian
@@ -2,48 +2,56 @@
 #
 # 2026/07/24 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 
-trap '[ -n "${tmp_folder}" -a -d "${tmp_folder}" ] && rm -rf "${tmp_folder}"' QUIT
+set -euo pipefail
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
 export LANG=C
 
+# Check build commands
+for cmd in ar tar gzip pod2man mktemp du cut install
+do
+  command -v "$cmd" >/dev/null || {
+    echo "error: $cmd missing"
+    exit 1
+  }
+done
+
+# Temporary folder
 tmp_folder=$(mktemp --directory /tmp/sat-XXXXXX)
 [ -n "${tmp_folder}" ] && [ -d "${tmp_folder}" ] || exit 1
+
+# Clean at end of script in all case
+trap 'rm -rf "${tmp_folder:-}"' EXIT
 
 # Set Name and Version
 PKG_NAME=sat
 CODE_VERSION=$(./get-version)
 PKG_VERSION=1
+[ -n "${CODE_VERSION}" ] || {
+  echo "error: Empty version"
+  exit 1
+}
 
-# Create future tree
-mkdir -p "${tmp_folder}"/usr/bin
-mkdir -p "${tmp_folder}"/usr/libexec/sat
-mkdir -p "${tmp_folder}"/usr/share/man/man1
-mkdir -p "${tmp_folder}"/usr/share/man/man8
-mkdir -p "${tmp_folder}"/usr/share/sat
-mkdir -p "${tmp_folder}"/usr/lib/systemd/system
-#mkdir -p "${tmp_folder}"/etc/bash_completion.d
+# Install files
+install -Dm 0755 -t "${tmp_folder}"/usr/bin/                sat
+install -Dm 0755 -t "${tmp_folder}"/usr/bin/                satq
+install -Dm 0755 -t "${tmp_folder}"/usr/bin/                satrm
+install -Dm 0755 -t "${tmp_folder}"/usr/libexec/sat/        sat-run
+install -Dm 0644 -t "${tmp_folder}"/usr/lib/systemd/system/ sat-run@.service
+install -Dm 0644 -t "${tmp_folder}"/usr/share/sat/          LICENSE.md
 
 # Create manuals
+mkdir -p "${tmp_folder}"/usr/share/man/man1
+mkdir -p "${tmp_folder}"/usr/share/man/man8
 pod2man --section=1 --release="SAT" sat.pod     | gzip > "${tmp_folder}"/usr/share/man/man1/sat.1.gz
 pod2man --section=1 --release="SAT" satq.pod    | gzip > "${tmp_folder}"/usr/share/man/man1/satq.1.gz
 pod2man --section=1 --release="SAT" satrm.pod   | gzip > "${tmp_folder}"/usr/share/man/man1/satrm.1.gz
 pod2man --section=8 --release="SAT" sat-run.pod | gzip > "${tmp_folder}"/usr/share/man/man8/sat-run.8.gz
 
-# Copy files
-cp sat satq satrm       "${tmp_folder}"/usr/bin/
-cp sat-run              "${tmp_folder}"/usr/libexec/sat/
-cp sat-run@.service     "${tmp_folder}"/usr/lib/systemd/system/
-cp LICENSE.md           "${tmp_folder}"/usr/share/sat/
-#cp sat.bash_completion  "${tmp_folder}"/etc/bash_completion.d/
-
 # Good right
-chmod -R a+rx        "${tmp_folder}"/usr/bin/sat*
-chmod -R a+rx        "${tmp_folder}"/usr/libexec/sat/sat-run
 chmod -R a+rX,go-w   "${tmp_folder}"/usr
 
 # Data archive
-rm -f "${tmp_folder}"/data.tar.gz
 (cd "${tmp_folder}" || exit 1; tar --owner root --group root -czf data.tar.gz ./usr)
 
 # Control file
@@ -53,9 +61,9 @@ Version: ${CODE_VERSION}-${PKG_VERSION}
 Section: utils
 Tag: implemented-in::bash, interface::commandline, role::program
 Priority: optional
-Depends: bash, systemd
+Depends: bash, systemd, coreutils, sed, grep
 Architecture: all
-Installed-Size: $(du -ks "${tmp_folder}"|cut -f 1)
+Installed-Size: $(du -ks "${tmp_folder}/usr"|cut -f 1)
 Maintainer: Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
 Description: Simple At Scheduler
  SAT is a lightweight one-shot job scheduler for Linux systems using
@@ -67,8 +75,9 @@ END
 # Post install and post remove
 cat <<END > "${tmp_folder}"/postinst
 #!/bin/sh
+set -e
 
-/usr/bin/systemctl daemon-reload
+/usr/bin/systemctl daemon-reload >/dev/null || true
 END
 cp "${tmp_folder}"/postinst "${tmp_folder}"/postrm
 chmod a+rx,go-w "${tmp_folder}"/postinst "${tmp_folder}"/postrm
@@ -83,9 +92,6 @@ echo 2.0 > "${tmp_folder}"/debian-binary
 # Create package (control before data)
 ar -r "${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}"_all.deb "${tmp_folder}"/debian-binary "${tmp_folder}"/control.tar.gz "${tmp_folder}"/data.tar.gz
       
-# Clean
-rm -rf "${tmp_folder}"
-
 # Prepare reprepro upload
 echo "# Prepare reprepro upload"
 echo "( cd /srv/www/debian/ || exit 1; reprepro includedeb trixie   ~/trixie/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
